# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botkube < Formula
  desc "Botkube CLI is a command line tool for managing Botkube resources"
  homepage "https://botkube.io"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/botkube/releases/download/v1.8.0/botkube-darwin-amd64", using: CurlDownloadStrategy
      sha256 "c6415586cc1c48f9b5945b9a6200cead39c11df764f1f88463f13eb44d3189f6"

      def install
        bin.install "botkube-darwin-amd64" => "botkube"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/botkube/releases/download/v1.8.0/botkube-darwin-arm64", using: CurlDownloadStrategy
      sha256 "d005a1608464d3147367478e2bbba25000180fe4481e8e292e1b2474da4b0c29"

      def install
        bin.install "botkube-darwin-arm64" => "botkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/botkube/releases/download/v1.8.0/botkube-linux-amd64", using: CurlDownloadStrategy
      sha256 "35773e50b8161c717029a9a0f4d153bf8b1772628ee5371513edeb4a8ea38abf"

      def install
        bin.install "botkube-linux-amd64" => "botkube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/botkube/releases/download/v1.8.0/botkube-linux-arm64", using: CurlDownloadStrategy
      sha256 "5da0ac6c8f281b8f270d5fa848ac95d2f0a54394734276330ef6d2806098309c"

      def install
        bin.install "botkube-linux-arm64" => "botkube"
      end
    end
  end

  test do
    system "#{bin}/botkube version -o=short"
  end
end
