# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Botkube < Formula
  desc "Botkube CLI is a command line tool for managing Botkube instances"
  homepage "https://botkube.io"
  version "1.2.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/botkube/releases/download/v1.2.0-rc.1/botkube_1.2.0-rc.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0bd1d123925085b21333ef611da14fcea03b8be04e1409cb4b7f8dc19a5ae034"

      def install
        bin.install "botkube"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/botkube/releases/download/v1.2.0-rc.1/botkube_1.2.0-rc.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "052c152cdcb1695f339e1ec52ccb83b64e1fd9bbaab221147e86829ed30fdd44"

      def install
        bin.install "botkube"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/botkube/releases/download/v1.2.0-rc.1/botkube_1.2.0-rc.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "d17519eea628426d119af832adad783d7c46f15a2ebc286ff43576b83efe4ed9"

      def install
        bin.install "botkube"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/botkube/releases/download/v1.2.0-rc.1/botkube_1.2.0-rc.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ab48a791da6eeeb697345e8ef10bbd392dc577b82b633555f0ac1c59984a66e0"

      def install
        bin.install "botkube"
      end
    end
  end
end
